In [2]:
import pandas as pd

In [4]:
inflation = pd.read_csv("data/inflation_unemployment_data.csv")
inflation.head()

   date  Inflation (annual %)  Unemployment rate (%)
0  2022              7.967574                    NaN
1  2021              3.466926               6.190663
2  2020              1.920968               6.708983
3  2019              2.206073               5.864570
4  2018              2.450362               5.979186

In [5]:
world_gdp = pd.read_csv("data/world_gdp_growth_data.csv")
world_gdp.head()

   date  GDP growth (annual %)
0  2022               3.089607
1  2021               6.259851
2  2020              -2.932043
3  2019               2.642216
4  2018               3.286613

In [6]:
usd_eur = pd.read_csv("data/usd_eur_exchange_rates_alpha_vantage.csv")
usd_eur.head()

   Unnamed: 0     Open     High      Low    Close
0  2024-11-05  0.91940  0.91950  0.91740  0.91770
1  2024-11-04  0.92220  0.92270  0.91680  0.91790
2  2024-10-31  0.91860  0.92179  0.91709  0.91860
3  2024-10-30  0.92088  0.92208  0.91841  0.92088
4  2024-10-29  0.92416  0.92507  0.92024  0.92416

In [7]:
event = pd.read_csv("data/scraped_calendar_events.csv")
event

            Date                      Event  Actual Forecast Previous
0     jan03.2007   US ISM Manufacturing PMI    51.4     51.0     49.5
1     jan04.2007      US Factory Orders m/m    0.9%     1.5%    -4.5%
2     jan04.2007        US ISM Services PMI    57.1     58.0     58.9
3     jan04.2007   US Crude Oil Inventories   -1.3M    -2.0M    -8.1M
4     jan04.2007  US Distillate Inventories    2.0M     0.9M     0.5M
...          ...                        ...     ...      ...      ...
2592  dec08.2010   US Crude Oil Inventories   -3.8M    -1.3M     1.1M
2593  dec08.2010  US Distillate Inventories    2.2M    -0.9M    -0.2M
2594  dec08.2010    US Gasoline Inventories    3.8M    -0.3M     0.6M
2595  dec09.2010     US Natural Gas Storage    -89B     -83B     -23B
2596  dec10.2010           US Trade Balance  -38.7B   -43.5B   -44.6B

[2597 rows x 5 columns]

In [9]:
event['Event'].unique()

array(['US ISM Manufacturing PMI', 'US Factory Orders m/m',
       'US ISM Services PMI', 'US Crude Oil Inventories',
       'US Distillate Inventories', 'US Gasoline Inventories',
       'EZ Consumer Confidence', 'CA Employment Change',
       'CA Unemployment Rate', 'US Average Hourly Earnings m/m',
       'US Non-Farm Employment Change', 'US Unemployment Rate',
       'US Natural Gas Storage', 'US Trade Balance',
       'US Retail Sales m/m', 'US Capacity Utilization Rate',
       'US Industrial Production m/m', 'US Core CPI m/m', 'US CPI m/m',
       'US Advance GDP q/q'], dtype=object)